### ISSUE TITLE
The result of five_point_ransac() is not fixed

### ISSUE THREAD

**Issue by zsz00** [pxl-th/RecoverPose.jl#14]
I use five_point_ransac() to solve E, P, but run several times with same parameters, the result of E,P, n_inliers is not same. 
why? 

julia v1.6.3 

n_inliers, (E, P, inliers, best_repr_error) = five_point_ransac(previous_points, current_points, K, K, GEEV4x4Cache())

**Comment by pxl-th** [comment]
Most likely due to different random samples being drawn from data each time you run it.
This causes the algorithm to converge to different results.

In practice, however, I find this algorithm to be quite noisy. If you're using it for pose recovery over several frames, I'd recommend using something like bundle adjustment on top of it to optimize poses once you've recovered them.

**Comment by zsz00** [comment]
I'm doing self-calibration for multiple cameras. 
previous_points, current_points  K are all pre-made data. 

n_inliers, (E, P, inliers, best_repr_error)  = five_point_ransac(previous_points, current_points, K, K, GEEV4x4Cache())
run several times, E,P is not same. 


And i try the essential_ransac(previous_points_pd, current_points_pd, focal_sum; threshold = 1.0)  have error: 
ERROR: LoadError: BoundsError: attempt to access Tuple{SMatrix{3, 3, Float64, 9}, Vector{Bool}, Float64} at index [4]
Stacktrace:
 [1] indexed_iterate(t::Tuple{SMatrix{3, 3, Float64, 9}, Vector{Bool}, Float64}, i::Int64, state::Int64)
   @ Base ./tuple.jl:86
 [2] camera_1()
   @ Main ~/codes/AutoCab.jl/src/test_2.jl:69
 [3] top-level scope
   @ ~/codes/AutoCab.jl/src/test_2.jl:99

**Comment by pxl-th** [comment]
Looks like the error is in your code and I'm assuming you're trying to unpack the returned result.
There's error in documentation for `essential_ransac`. It returns `n_inliers, (E, inliers, error)`, without `P` projecton matrix, 
but looks like you are trying to unpack it to `n_inliers, (E, P, inliers, error)`.

**Comment by zsz00** [comment]
n_inliers, (E, inliers, error) = essential_ransac(previous_points_pd, current_points_pd, focus_sum; threshold = 1.0)
is ok !!!

but the doc is bad:
![image](https://user-images.githubusercontent.com/12711073/141306199-85b4a4bc-5bfc-4a30-a7f4-b6da3965ed98.png)

**Comment by zsz00** [comment]
n_inliers, (E, inliers, best_repr_error) = essential_ransac(previous_points, current_points, focal_sum; threshold = 1.0)
best_n_inliers, P_res, best_inliers, best_error = recover_pose(E, pixels1, pixels2, K1, K2; threshold = 1.0)

Is this better than five_point_ransac() ??

**Comment by pxl-th** [comment]
Agree, the documentation can be improved.
I find the `five_point_ransac` to be actually better, because it evaluates both essential matrix and recovered poses from it, while `essential_ransac` only evaluates essential matrix, from which you then evaluate only 4 possible poses.

**Comment by zsz00** [comment]
I see, thanks for your reply !!

**Comment by pxl-th** [comment]
The documentation is fixed, thanks for pointing out. Closing this, feel free to re-open though.
